In [8]:
import numpy as np

In [9]:
def  gaussian(x):
    mu = np.array([[2],
                   [2]])
    sigma = np.array([[10, 0],
                      [0, 10]])
    xm = x - mu
    result = np.exp((-1/2) * xm.T @ np.linalg.inv(sigma) @ xm)
    return result

In [10]:
x, y = np.arange(5), np.arange(5)
xLen, yLen = len(x), len(y)
z1 = np.zeros((xLen, yLen))

for y_index in range(yLen):
        for x_index in range(xLen):
            element = np.array([[x[x_index]],
                                [y[y_index]]])
            result = gaussian(element)
            z1[y_index][x_index] = result

z1

array([[0.67032005, 0.77880078, 0.81873075, 0.77880078, 0.67032005],
       [0.77880078, 0.90483742, 0.95122942, 0.90483742, 0.77880078],
       [0.81873075, 0.95122942, 1.        , 0.95122942, 0.81873075],
       [0.77880078, 0.90483742, 0.95122942, 0.90483742, 0.77880078],
       [0.67032005, 0.77880078, 0.81873075, 0.77880078, 0.67032005]])

# ________________________-

In [11]:
nx, ny = 5, 5
x, y = np.arange(nx), np.arange(ny)
X, Y = np.meshgrid(x, y, indexing= 'xy')
element = np.array([[X],
                    [Y]])
# Stack X and Y into a nx x ny x 2 array
XY = np.dstack([X, Y])

In [12]:
def  gaussian(x):
    # Note that I have removed the extra dimension: 
    # mu is a simple array of shape (2,)
    # This is no problem, since we're using einsum
    # for the matrix multiplication
    mu = np.array([2, 2])
    sigma = np.array([[10, 0],
                      [0, 10]])
    # Broadcast xm to x's shape: (nx, ny, 2)
    xm = x - mu[..., :]
    invsigma = np.linalg.inv(sigma)
    # Compute the (double) matrix multiplication
    # Leave the first two dimension (ab) alone
    # The other dimensions will sum up to a single scalar
    # and thus only the ab dimensions are there in the output
    alpha = np.einsum('abi,abj,ji->ab', xm, xm, invsigma)
    result = np.exp((-1/2) * alpha)
    # The shape of result is (nx, ny)
    return result


In [13]:
z2 = gaussian(XY)

z2


array([[0.67032005, 0.77880078, 0.81873075, 0.77880078, 0.67032005],
       [0.77880078, 0.90483742, 0.95122942, 0.90483742, 0.77880078],
       [0.81873075, 0.95122942, 1.        , 0.95122942, 0.81873075],
       [0.77880078, 0.90483742, 0.95122942, 0.90483742, 0.77880078],
       [0.67032005, 0.77880078, 0.81873075, 0.77880078, 0.67032005]])

In [15]:
np.array_equal(z1,z2)

True

# ____________________

In [51]:
def  gaussian(x):

    mu = np.array([[2],
                   [2]])          
    sigma = np.array([[10, 0],
                      [0, 10]])

    xm = x - mu
    result = np.exp((-1/2) * xm.T @ np.linalg.inv(sigma) @ xm)
    return result

In [52]:
x, y = np.arange(5), np.arange(5)

coordinates = []
for i in x:
    for j in y:
        coordinates.append((j,i))

coordinates = np.stack(coordinates).T

print(coordinates)

[[0 1 2 3 4 0 1 2 3 4 0 1 2 3 4 0 1 2 3 4 0 1 2 3 4]
 [0 0 0 0 0 1 1 1 1 1 2 2 2 2 2 3 3 3 3 3 4 4 4 4 4]]


In [53]:
gaussian(coordinates).shape

(25, 25)